import{i as h,S as $}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const v="46887087-5e19c9c0c2a23badfaaee9a20",E="https://pixabay.com/api/";async function y(t,o=1,a=15){const n=`${E}?key=${v}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${a}`;try{const e=await fetch(n);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error(e),e}}function g(t){const o=document.querySelector(".gallery"),a=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:c,views:b,comments:q,downloads:S})=>`
    <a class="gallery-item" href="${e}">
      <img src="${n}" alt="${r}" loading="lazy" />
      <div class="info">
        <p><strong>Likes:</strong> ${c}</p>
        <p><strong>Views:</strong> ${b}</p>
        <p><strong>Comments:</strong> ${q}</p>
        <p><strong>Downloads:</strong> ${S}</p>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",a)}function P(){document.querySelector(".gallery").innerHTML=""}function i(t,o){t==="error"?h.error({title:"Error",message:o}):h.success({title:"Success",message:o})}let m=new $(".gallery a",{captionsData:"alt",captionDelay:250});const B=document.querySelector(".search-form"),f=document.querySelector(".load-more"),p=document.querySelector(".loader");let s=1,l="",u=0;function w(){p.style.display="block"}function L(){p.style.display="none"}function I(){f.hidden=!1}function d(){f.hidden=!0}B.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.query,a=o.value.trim();if(!a){i("error","Please enter a search term.");return}P(),s=1,l=a,o.value="",d(),w();try{const n=await y(l,s);if(u=n.totalHits,n.hits.length===0){i("error","No images matching your search query. Try again!");return}g(n.hits),m.refresh(),I(),(n.hits.length<15||s*15>=u)&&(d(),i("info","We're sorry, but you've reached the end of search results."))}catch{i("error","Failed to fetch images.")}finally{L()}});f.addEventListener("click",async()=>{s+=1,w();try{const t=await y(l,s);g(t.hits),m.refresh(),M(),s*15>=u&&(d(),i("info","We're sorry, but you've reached the end of search results."))}catch{i("error","Failed to load more images.")}finally{L()}});function M(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
